# vim: set nospell:

application: qa-for-google
module: default
version: 1
runtime: python27
api_version: 1
threadsafe: true

instance_class: F2
automatic_scaling:
  min_idle_instances: 1
  min_pending_latency: 30ms
  max_pending_latency: 150ms


builtins:
- deferred: on
- remote_api: on
- appstats: on

inbound_services:
- warmup

handlers:

- url: /.*
  script: default.app

libraries:
- name: markupsafe
  version: "latest"
- name: setuptools
  version: "0.6c11"
- name: jinja2
  version: "2.6"
- name: pycrypto
  version: "2.6"
- name: ssl
  version: "latest"

